/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'createdAt' : Time,
  'orderId' : IDL.Text,
  'totalAmountCents' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
  'buyerName' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'priceCents' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(OrderItem)],
      [IDL.Text],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const Order = IDL.Record({
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'createdAt' : Time,
    'orderId' : IDL.Text,
    'totalAmountCents' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
    'buyerName' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'priceCents' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(OrderItem)],
        [IDL.Text],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };