/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'createdAt' : Time,
  'orderId' : string,
  'totalAmountCents' : bigint,
  'items' : Array<OrderItem>,
  'buyerName' : string,
}
export interface OrderItem { 'productId' : string, 'quantity' : bigint }
export type OrderStatus = { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : string,
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : string,
  'category' : string,
  'priceCents' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getOrder' : ActorMethod<[string], Order>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'placeOrder' : ActorMethod<[string, string, Array<OrderItem>], string>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];